/**
 * GenerationData represents the energy generation data for a single type of fuel.
 * @property {string} fuel - The type of fuel.
 * @property {number} perc - The percentage of energy generated by this type of fuel.
 */
interface IGenerationData {
    fuel: string;
    perc: number;
}

export default IGenerationData;